#!/usr/bin/env python3
"""
YOLOv11 ambulance detector -- training wrapper for Green Wave++

Thin wrapper around Ultralytics' training API.  Handles:
  - Dataset YAML discovery (prefers vision/data/dataset.yaml)
  - Backbone selection (yolo11n / yolo11s on disk already)
  - Resume from partial training run
  - Post-training weight copy to vision/models/

Usage:
    python vision/train.py
    python vision/train.py --model yolo11s.pt --epochs 100 --resume
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

# greenwave/ root
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def find_dataset_yaml(vision_dir: Path) -> Path:
    # Prefer our own dataset.yaml (generated by prepare_data.py)
    candidates = [
        vision_dir / "data" / "dataset.yaml",
        vision_dir / "data.yaml",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError(
        f"No dataset YAML found.  Run:\n"
        f"  python vision/prepare_data.py --roboflow <download_dir> --verify"
    )


def find_pretrained(vision_dir: Path, model_name: str) -> str:
    """
    Prefer a locally cached .pt file so we don't hit the network.
    Falls back to letting Ultralytics download it automatically.
    """
    local = vision_dir / model_name
    if local.exists():
        print(f"[OK] Using local backbone: {local}")
        return str(local)

    # Also check greenwave/ root
    root_local = ROOT / model_name
    if root_local.exists():
        print(f"[OK] Using local backbone: {root_local}")
        return str(root_local)

    print(f"  Backbone {model_name} not found locally -- Ultralytics will download it")
    return model_name


def train(args: argparse.Namespace) -> None:
    from ultralytics import YOLO

    vision_dir  = ROOT / "vision"
    data_yaml   = find_dataset_yaml(vision_dir)
    pretrained  = find_pretrained(vision_dir, args.model)
    models_dir  = vision_dir / "models"
    models_dir.mkdir(exist_ok=True)

    print("=" * 60)
    print("Green Wave++ -- YOLOv11 Ambulance Detector Training")
    print("=" * 60)
    print(f"  Backbone : {pretrained}")
    print(f"  Dataset  : {data_yaml}")
    print(f"  Epochs   : {args.epochs}")
    print(f"  Img size : {args.imgsz}")
    print(f"  Batch    : {args.batch}")
    print()

    model = YOLO(pretrained)

    # Check for an existing partial run to resume
    last_run_weights = vision_dir / "runs" / "detect" / "greenwave" / "weights" / "last.pt"
    if args.resume and last_run_weights.exists():
        print(f"▶ Resuming from {last_run_weights}")
        model = YOLO(str(last_run_weights))

    results = model.train(
        data         = str(data_yaml),
        epochs       = args.epochs,
        imgsz        = args.imgsz,
        batch        = args.batch,
        name         = "greenwave",
        project      = str(vision_dir / "runs" / "detect"),
        device       = args.device,
        patience     = args.patience,
        save_period  = 10,
        exist_ok     = args.resume,
        # Augmentation tuned for emergency vehicle detection
        degrees      = 5.0,
        flipud       = 0.0,   # vehicles are not upside-down
        fliplr       = 0.5,
        mosaic       = 1.0,
        mixup        = 0.1,
        hsv_h        = 0.015,
        hsv_s        = 0.5,
        hsv_v        = 0.3,
    )

    # Copy best weights to vision/models/ for easy access by infer.py
    best_weights = (
        vision_dir / "runs" / "detect" / "greenwave" / "weights" / "best.pt"
    )
    if best_weights.exists():
        dest = models_dir / "yolov11-ambulance.pt"
        shutil.copy2(best_weights, dest)
        print(f"\n[OK] Best weights copied -> {dest}")
        print(f"   Update safety_config or config.yaml with this path.")
    else:
        print(f"\n[WARN]  best.pt not found at expected path: {best_weights}")

    # Quick eval summary
    metrics = model.val(data=str(data_yaml))
    print(f"\nValidation metrics:")
    print(f"  mAP@50    : {metrics.box.map50:.4f}")
    print(f"  Precision : {metrics.box.mp:.4f}")
    print(f"  Recall    : {metrics.box.mr:.4f}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Train YOLOv11 ambulance detector")
    ap.add_argument("--model",    default="yolo11s.pt",
                    help="YOLO model variant (yolo11n.pt, yolo11s.pt, ...)")
    ap.add_argument("--epochs",   type=int,   default=80)
    ap.add_argument("--imgsz",    type=int,   default=640)
    ap.add_argument("--batch",    type=int,   default=16)
    ap.add_argument("--device",   default="0",
                    help="CUDA device index or 'cpu'")
    ap.add_argument("--patience", type=int,   default=15,
                    help="Early stopping patience (epochs)")
    ap.add_argument("--resume",   action="store_true",
                    help="Resume from last checkpoint if available")
    args = ap.parse_args()

    train(args)


if __name__ == "__main__":
    main()
