#!/usr/bin/env python3
"""
API key + WebSocket tokens -- Green Wave++

The API key never lives in config.yaml (that file is committed). Resolution
order, first hit wins:

  1. the env var named by security.api_key_env  (docker / CI / cloud)
  2. `api_key:` in the gitignored secrets file   (normal dev machine)
  3. nothing anywhere -> generate one, save it to the secrets file so it
     survives restarts, and report it as freshly generated

Browsers can't put custom headers on a WebSocket, so the dashboard trades
the API key for a short-lived token (POST /token) and hands that token
over as a query parameter when it connects. Tokens expire after
security.ws_token_ttl_sec and live only in server memory -- a leaked
dashboard URL goes stale in minutes, unlike a leaked key.
"""

from __future__ import annotations

import os
import secrets
import time
from pathlib import Path
from typing import Dict, Optional, Tuple

import yaml

ROOT = Path(__file__).resolve().parents[1]


def resolve_api_key(sec_cfg: dict, root: Path = ROOT) -> Tuple[str, str]:
    """Returns (key, source) with source one of 'env' | 'file' | 'generated'."""
    env_name = sec_cfg.get("api_key_env", "GREENWAVE_API_KEY")
    key = os.environ.get(env_name, "").strip()
    if key:
        return key, "env"

    secrets_path = root / sec_cfg.get("secrets_file", "common/secrets.yaml")
    if secrets_path.exists():
        data = yaml.safe_load(secrets_path.read_text()) or {}
        key = str(data.get("api_key") or "").strip()
        if key:
            return key, "file"

    key = secrets.token_urlsafe(32)
    secrets_path.parent.mkdir(parents=True, exist_ok=True)
    secrets_path.write_text(
        "# Auto-generated by Green Wave++ -- gitignored.\n"
        "# Delete this file to rotate the key on the next start.\n"
        f"api_key: {key}\n"
    )
    return key, "generated"


class WSTokenStore:
    """Short-lived bearer tokens for the dashboard WebSocket. In-memory only."""

    def __init__(self, ttl_sec: float = 300.0, now=time.time):
        self.ttl    = float(ttl_sec)
        self._now   = now
        self._live: Dict[str, float] = {}   # token -> expiry timestamp

    def issue(self, ttl_sec: Optional[float] = None) -> Tuple[str, float]:
        token   = secrets.token_urlsafe(24)
        expires = self._now() + (self.ttl if ttl_sec is None else float(ttl_sec))
        self._live[token] = expires
        self._purge()
        return token, expires

    def validate(self, token: str) -> bool:
        self._purge()
        return bool(token) and token in self._live

    def _purge(self) -> None:
        now = self._now()
        for tok, exp in list(self._live.items()):
            if exp <= now:
                del self._live[tok]
